#!/usr/bin/env node
/**
 * setup.js
 * Run after deployment: node scripts/setup.js
 * Automatically updates all config files with deployed contract addresses.
 */

const fs   = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");

console.log("╔══════════════════════════════════════════╗");
console.log("║     AgentForge Post-Deploy Setup         ║");
console.log("╚══════════════════════════════════════════╝\n");

// ─── 1. Read deployment ───────────────────────────────────────────────────────

const deployFile = path.join(ROOT, "deployments.json");
if (!fs.existsSync(deployFile)) {
  console.error("❌ deployments.json not found. Run 'npm run deploy:base' first.");
  process.exit(1);
}

const deployment = JSON.parse(fs.readFileSync(deployFile, "utf8"));
const contracts  = deployment.contracts;

console.log("✅ Found deployment:");
console.log(`   Network:  ${deployment.network} (chainId: ${deployment.chainId})`);
console.log(`   Registry: ${contracts.AgentRegistry}`);
console.log(`   Vault:    ${contracts.AgentVault}`);
console.log(`   Commerce: ${contracts.AgentCommerce}`);
if (contracts.AgentExecutor) console.log(`   Executor: ${contracts.AgentExecutor}`);
console.log();

// ─── 2. Update .env ───────────────────────────────────────────────────────────

const envPath = path.join(ROOT, ".env");
if (!fs.existsSync(envPath)) {
  if (fs.existsSync(path.join(ROOT, ".env.example"))) {
    fs.copyFileSync(path.join(ROOT, ".env.example"), envPath);
    console.log("📄 Created .env from .env.example");
  } else {
    fs.writeFileSync(envPath, "");
    console.log("📄 Created empty .env");
  }
}

let envContent = fs.readFileSync(envPath, "utf8");

const updates = {
  REGISTRY_ADDRESS: contracts.AgentRegistry,
  COMMERCE_ADDRESS: contracts.AgentCommerce,
  VAULT_ADDRESS:    contracts.AgentVault,
  EXECUTOR_ADDRESS: contracts.AgentExecutor ?? "0x0000000000000000000000000000000000000000",
  REACT_APP_REGISTRY_ADDRESS: contracts.AgentRegistry,
  REACT_APP_COMMERCE_ADDRESS: contracts.AgentCommerce,
  REACT_APP_VAULT_ADDRESS:    contracts.AgentVault,
  REACT_APP_EXECUTOR_ADDRESS: contracts.AgentExecutor ?? "0x0000000000000000000000000000000000000000",
};

for (const [key, value] of Object.entries(updates)) {
  const regex = new RegExp(`^${key}=.*$`, "m");
  if (regex.test(envContent)) {
    envContent = envContent.replace(regex, `${key}=${value}`);
  } else {
    envContent += `\n${key}=${value}`;
  }
}

fs.writeFileSync(envPath, envContent);
console.log("✅ Updated .env with contract addresses");

// ─── 3. Update dashboard ──────────────────────────────────────────────────────

const dashEnvPath = path.join(ROOT, "dashboard", ".env");
const dashEnv = `REACT_APP_API_URL=http://localhost:4000
REACT_APP_WS_URL=ws://localhost:4000
REACT_APP_REGISTRY_ADDRESS=${contracts.AgentRegistry}
REACT_APP_COMMERCE_ADDRESS=${contracts.AgentCommerce}
REACT_APP_VAULT_ADDRESS=${contracts.AgentVault}
REACT_APP_EXECUTOR_ADDRESS=${contracts.AgentExecutor ?? "0x0000000000000000000000000000000000000000"}
REACT_APP_CHAIN_ID=${deployment.chainId}
`;

fs.mkdirSync(path.join(ROOT, "dashboard"), { recursive: true });
fs.writeFileSync(dashEnvPath, dashEnv);
console.log("✅ Created dashboard/.env");

// ─── 4. Update docker-compose env ────────────────────────────────────────────

const dockerEnvPath = path.join(ROOT, "docker", ".env");
const dockerEnv = `# Auto-generated by setup.js — do not edit manually
REGISTRY_ADDRESS=${contracts.AgentRegistry}
COMMERCE_ADDRESS=${contracts.AgentCommerce}
VAULT_ADDRESS=${contracts.AgentVault}
EXECUTOR_ADDRESS=${contracts.AgentExecutor ?? "0x0000000000000000000000000000000000000000"}
`;

fs.mkdirSync(path.join(ROOT, "docker"), { recursive: true });
let existingDockerEnv = fs.existsSync(dockerEnvPath) ? fs.readFileSync(dockerEnvPath, "utf8") : "";
// Remove old auto-generated block
existingDockerEnv = existingDockerEnv.replace(/# Auto-generated[\s\S]*?EXECUTOR_ADDRESS=.*\n?/, "");
fs.writeFileSync(dockerEnvPath, dockerEnv + "\n" + existingDockerEnv.trim());
console.log("✅ Updated docker/.env");

// ─── 5. Check for missing keys ────────────────────────────────────────────────

console.log("\n── Checking configuration ──");

const requiredKeys = ["BASE_RPC_URL", "PRIVATE_KEY", "BASESCAN_API_KEY"];
const missingKeys  = [];

for (const key of requiredKeys) {
  const val = envContent.match(new RegExp(`^${key}=(.*)$`, "m"))?.[1] ?? "";
  if (!val || val.includes("YOUR_") || val === "0x0000000000000000000000000000000000000000") {
    missingKeys.push(key);
  }
}

if (missingKeys.length > 0) {
  console.log(`\n⚠️  Still need to set these in .env:`);
  missingKeys.forEach(k => console.log(`   - ${k}`));
}

// ─── 6. Check balances hint ───────────────────────────────────────────────────

console.log("\n── What to do next ──────────────────────────────────────────\n");
console.log("1. Fund your agent wallets on Base:");
console.log("   Yield agent:    needs ETH (gas) + USDC");
console.log("   Arb agent:      needs ETH (gas) + USDC");
console.log("   Oracle agent:   needs ETH (gas only)");
console.log();
console.log("2. Grant yourself the AUDITOR_ROLE on BaseScan:");
console.log(`   https://basescan.org/address/${contracts.AgentRegistry}#writeContract`);
console.log(`   → grantRole(AUDITOR_ROLE, your_wallet_address)`);
console.log(`   → AUDITOR_ROLE = 0x${Buffer.from("AUDITOR_ROLE").toString("hex").slice(0,8)}...`);
console.log();
console.log("3. Start the backend server:");
console.log("   npm run server");
console.log();
console.log("4. Start the dashboard:");
console.log("   npm run dashboard:dev");
console.log();
console.log("5. Register and audit your first agent through the dashboard");
console.log();
console.log("6. Start agents (after registering them):");
console.log("   npm run agent:yield    # yield optimizer");
console.log("   npm run agent:arb      # arbitrage bot");
console.log("   npm run agent:oracle   # data oracle");
console.log();
console.log("Or run everything with Docker:");
console.log("   npm run docker:up");
console.log();
console.log("─────────────────────────────────────────────────────────────\n");
console.log("🎉 Setup complete! Your contracts are live on Base.\n");
